version: '3'
services:
  backend:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
