version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
